# Generated by Django 3.0.2 on 2020-01-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex_data', '0002_auto_20200130_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
