# Generated by Django 3.0.2 on 2020-01-30 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forex_data', '0004_auto_20200130_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 18, 6, 35, 171923, tzinfo=utc)),
        ),
    ]
